- .env
- .gitignore
Credentials should not be committed, even with default data.
With **.env** marked as a git object, a probable mistake can happens when someone forgot to cleanup their own credentials.
> Avoid commit credentials

- .github/deny_list.sh
- .github/workflows/commit_checks.yaml
Minimal checks for:
* Commit done without validation on the origin ( Husky is not installed )
* Prevent to add yarn.lock file to not mixe up with npm package lock.
* Prevent add png, jpg, gif and tiff files. Only svg files are allowed.
> Add basic commit checks

- src/app/[locale]/components/components/ComponentsTable.tsx
- src/app/[locale]/components/detail/[id]/components/ReleaseOverview.tsx
- src/components/Attachments/Attachments.tsx
- src/components/ChangeLog/ChangeLogList/ChangeLogList.tsx
- src/components/ComponentVulnerabilities/ComponentVulnerabilities.tsx
- src/components/sw360/Table/Table.tsx
- src/components/sw360/Table/wrapper.tsx
1. [Grid.js] [ERROR] Duplicate plugin ID: pagination
2. [Grid.js] [ERROR] Duplicate plugin ID: search
3. [Grid.js] [ERROR]: The container element [object HTMLDivElement] is not empty. Make sure the container is empty and call render() again
4. [Warning] ReactDOM.render is no longer supported in React 18
> Fix Gridjs error and warning logs, add missing page size selector for component and release page

- src/components/sw360/Table/Table.tsx
Exposing the language structure from GridJs to our internal component.
Table will allow to set custom messages for specific parts of the table structure, like noRecordsFound, Next, Previous, etc.
The message should be set on the **Table** component  passing language structure in the format of GridJs own translation structure. 
Reference: [GridJs example](https://gridjs.io/docs/config/language) and the complete [GridJs structure](https://github.com/grid-js/gridjs/blob/master/src/i18n/en_US.ts)
Since we are not using the internal GridJs translation engine, but next-i18n from the point of view of the internal components of the table, it will always be treated as en_US and irrelevant for our code.
To do change from our Table component, we just need to pass the structure like stated above but …
> Expose language option to table

- src/app/[locale]/home/components/MySubscriptionsWidget.tsx
Added my subscriptions at home page
> feat(home_page): Added my subscriptions at home page

- src/app/[locale]/requests/components/OpenClearingRequest.tsx
Fixed open CR list table data based on CR status
Out of 10 status list, if the CR status is `REJECTED` and `CLOSED`, it will go to Closed CR list. Rest will be in Open CR list
> fix(CR): Fixed open CR list table data based on CR status

- messages/de.json
- messages/en.json
- messages/es.json
- messages/fr.json
- messages/ja.json
- messages/ko.json
- messages/pt-BR.json
- messages/vi.json
- messages/zh-CN.json
- messages/zh-TW.json
- src/app/[locale]/requests/clearingRequest/[id]/components/ClearingRequestDetail.tsx
Handle CR details and Open CR table if project is deleted after CR creation :
Open CR Table : 
- Show `Deleted Project` in open CR table.
- Show releases as `not available`
CR Details page :
- Disable edit CR button if project is deleted
- Change the CR details header for deleted project
> feat(CR): Added scenario to handle deleted project after CR creation

- src/app/[locale]/projects/add/page.tsx
- src/app/[locale]/projects/duplicate/[id]/components/DuplicateProject.tsx
- src/app/[locale]/projects/edit/[id]/components/EditProject.tsx
- src/utils/common.utils.ts
- Correct add/update/duplicate project when dependency network is disabled
- Handle null and undefined case for convertObjectToMapRoles
> Fix project dependency network off mode

- messages/de.json
- messages/en.json
- messages/es.json
- messages/fr.json
- messages/ja.json
- messages/ko.json
- messages/pt-BR.json
- messages/vi.json
- messages/zh-CN.json
- messages/zh-TW.json
- src/app/[locale]/components/detail/[id]/components/DetailOverview.tsx
- src/app/[locale]/components/releases/detail/[id]/components/DetailOverview.tsx
- src/object-types/Component.ts
Related back-end pull requests:
- https://github.com/eclipse-sw360/sw360/pull/2738
- https://github.com/eclipse-sw360/sw360/pull/2737
> Handle components/releases subscriptions

- src/components/sw360/SearchVendorsModal/VendorDialog.tsx
Vendors are fetched when the component is initialized.
Fetch vendors only when the user clicks on the Search button.
> fix(SearchVendors): Prevent fetching vendors on component initialization

- src/app/[locale]/components/releases/detail/[id]/components/ClearingDetails.tsx
- src/app/[locale]/projects/components/DeleteProjectDialog.tsx
- src/app/[locale]/projects/components/Projects.tsx
- src/app/[locale]/requests/clearingRequest/detail/[id]/components/ClearingRequestDetail.tsx
- src/app/[locale]/requests/components/BulkDeclineModerationRequestModal.tsx
- src/app/[locale]/requests/components/ClosedClearingRequest.tsx
- src/app/[locale]/requests/components/ClosedModerationRequest.tsx
- src/app/[locale]/requests/components/OpenClearingRequest.tsx
- src/app/[locale]/requests/components/OpenModerationRequest.tsx
- src/app/[locale]/requests/components/Requests.tsx
- src/object-types/Project.ts
1. [Delete Project] Enabled the Delete button.
2. [Project List] Fixed the behaviors of the Clearing Request icon.
3. [Edit & View Release] Corrected data in "License Scan Report Result," "Legal Evaluation," and "License Agreement" fields
4. [Request] Prevent application from signing out when visiting the Request page
---
- The user is logged in.
---
**Pre-condition:**
- There is at least one existing project.
**Procedure:**
- Option 1: On the Project list page, click the delete button in the Action column to delete a project.
- Option 2: On the Update Project page, click the "Delete Project" button.
**Expected:**
+ A "Delete Project" dialog appears with the message "Do you really want to delete the project?"
+ The project is successfully deleted after clicking the "Delete Project" …
> fix: issues in New Frontend

- src/app/[locale]/projects/detail/[id]/components/Summary.tsx
Fixed the Visibility field in Project detail page to display **"Group And Moderators" i**nstead of **"Buisnessunit And Moderators"**.
> Fixed Visibility field in Project detail

- src/app/[locale]/projects/detail/[id]/components/Administration.tsx
- src/object-types/AdministrationDataType.ts
Fixed license info header at `Administration` tab of project detail page
> fix(Project): Fixed license info header under project detail page

- src/app/[locale]/projects/add/page.tsx
- src/app/[locale]/projects/edit/[id]/components/EditProject.tsx
- src/components/ProjectAddSummary/Roles/DepartmentModal.tsx
- src/components/ProjectAddSummary/Roles/Roles.tsx
- Allow user to select a department in group field when creating or editing a project.
---
- Navigate to Create Project or Edit Project.
- Select the "Group" field, the Department selection appear.
- Click search and choose the appropriate department.
- Click Select and then Create Project or Update Project to complete the process.
> Fix: Choose a department in Group field (Create and Edit Project)

- src/components/sw360/AdvancedSearch/AdvancedSearch.tsx
**Description**
Added onKeyDown event listener for the string fields of Advanced search to call the onSubmit function when the pressed key is Enter.
This makes the user experience more intuitive as they they don't have to scroll to the bottom to press the "Submit" button.
> feat(AdvancedSearch): Submit search on Enter

- src/app/[locale]/home/components/HomeTableHeader.tsx
- src/app/[locale]/home/components/MyComponentsWidget.tsx
- src/app/[locale]/home/components/MyProjectsWidget.tsx
- src/app/[locale]/home/components/MySubscriptionsWidget.tsx
- src/app/[locale]/home/components/MyTaskAssignmentsWidget.tsx
- src/app/[locale]/home/components/MyTaskSubmissionsWidget.tsx
- src/app/[locale]/home/components/RecentComponentsWidget.tsx
- src/app/[locale]/home/components/RecentReleasesWidget.tsx
fixes#527 reload button by adding a state variable reload and addition it to useEffect dependency
> Fix(home): Add reload button for all tables 

- src/components/sw360/AdvancedSearch/AdvancedSearch.tsx
Reverts eclipse-sw360/sw360-frontend#639
Hey @heliocastro and @VAIBHAVSING !
I think we need to revert this PR. Because the param `luceneSearch=true` is required for couple of fields (`group`, `tag` and `additionalData`) of adv search at project page.
> Revert : "fix(component): Advance Search"

- src/app/api/auth/[...nextauth]/keycloakAuthOption.ts
- src/utils/env.ts
!BREAKING: Update the variables `NEXT_PUBLIC_SW360_REST_CLIENT_ID` and `NEXT_PUBLIC_SW360_REST_CLIENT_SECRET` to server side variables only. This would require updating existing `.env` files.
From:
```ini
NEXT_PUBLIC_SW360_AUTH_PROVIDER='sw360oauth'
NEXT_PUBLIC_SW360_REST_CLIENT_ID='trusted-sw360-client'
NEXT_PUBLIC_SW360_REST_CLIENT_SECRET='sw360-secret'
```
To:
```ini
NEXT_PUBLIC_SW360_AUTH_PROVIDER='sw360oauth'
SW360_REST_CLIENT_ID='trusted-sw360-client'
SW360_REST_CLIENT_SECRET='sw360-secret'
```
> fix(env)!: Make oauth vars server side only

- src/app/[locale]/projects/generateLicenseInfo/[id]/components/GenerateLicenseInfo.tsx
Fixed infinite rendering at `Generate License Info` at `License clearing` tab of project detail page.
Closes #708
> fix(Project): Fixed `Generate License Info` at project detail page

- src/app/[locale]/components/editRelease/[id]/components/EditRelease.tsx
- src/app/[locale]/components/releases/detail/[id]/components/DetailOverview.tsx
When clicking "**Edit release**," users now stay on the same tab (e.g., Attachments, Clearing Details) instead of always being redirected to Summary.
Closes : #689
> fix(Release): Preserve tab selection on clicking edit release button

- src/app/[locale]/ecc/components/ECC.tsx
Removed extra data `(eccn)` passed to ecc overview table.
Closes : https://github.com/eclipse-sw360/sw360-frontend/issues/811
> fix(ECC): Removed extra data passed to ecc overview table

- src/app/[locale]/licenses/detail/components/Detail.tsx
- src/object-types/LicenseDetail.ts
Added missing data of `License Type` at `License` detail page
Closes : https://github.com/eclipse-sw360/sw360-frontend/issues/882
> fix(Licenses): Added missing `License Type` at `License` detail page

- package.json
- pnpm-lock.yaml
Fixed vulnerable (High Severity) `@eslint/plugin-kit 0.3.1` --> `@eslint/plugin-kit 0.3.3` with override in `package.json` due to multiple transitive dependencies.
```
@eslint/compat 1.3.1  ...  @eslint/plugin-kit 0.3.1
@typescript-eslint/eslint-plugin 8.33.0  ...  @eslint/plugin-kit 0.3.1
@typescript-eslint/parser 8.33.0  ...  @eslint/plugin-kit 0.3.1
eslint 9.28.0  @eslint/plugin-kit 0.3.1
eslint-config-next 15.3.5  ...  @eslint/plugin-kit 0.3.1
eslint-import-resolver-typescript 4.4.3  ...  @eslint/plugin-kit 0.3.1
eslint-plugin-import 2.32.0  ...  @eslint/plugin-kit 0.3.1
eslint-plugin-prettier 5.5.1  ...  @eslint/plugin-kit 0.3.1
eslint-plugin-react 7.37.5  ...  @eslint/plugin-kit 0.3.1
eslint-plugin-simple-import-sort 12.1.1  ...  @eslint/plugin-kit 0.3.1
typescript-eslint 8.35.1 …
```
> fix(npm): Fixed eslint-plugin-kit vulnerability

- src/app/[locale]/projects/components/Projects.tsx
- src/app/[locale]/projects/detail/[id]/components/LicenseClearing.tsx
- src/app/[locale]/projects/detail/[id]/components/ProjectDetailTab.tsx
Closes : #960 
Currently the view CR modal is not being picked up in both License Clearing and Projects tab even if CR exists for a project.
Rebase with latest backend main for testing.
> fix(CR): Added fix for clearing request view.
