CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Add missing README, CODE_OF_CONDUCT, CONTRIBUTING

Add initial base project docs

---

.eslintrc.json
.gitignore
package.json
tsconfig.json

Upgrade to Next.js 13.4

---

.github/workflows/build.yaml
.licenserc.yaml
next.config.js
package.json
src/components/AddKeyValue.tsx
src/components/Navbar.tsx
src/components/SelectCountry.tsx
src/components/component/advance.search.tsx
src/components/component/delete.component.dialog.tsx
src/components/component/list.components.tsx
src/object-types/Constants.ts
src/pages/[projects]/[add]/administration.tsx
src/pages/[projects]/[add]/linkedProjects.tsx
src/pages/[projects]/index.tsx
src/pages/components/index.tsx
src/services/auth.service.ts
src/services/home.service.ts
src/services/projects.service.ts
src/utils/api/api.util.ts
src/utils/common.utils.ts
src/utils/pagination/Pagination.tsx
src/utils/pagination/usePagination.tsx

- Fix all Typescript related errors check on build.
- Added CI build to check errors on deployment.
TODO: Decide if warnings should be considered error on production builds.

Fix build errors and add build check

---

src/components/ProfileDropdown/ProfileDropdown.module.css
src/components/ProfileDropdown/ProfileDropdown.tsx
src/components/SW360Navbar/SW360Navbar.module.css
src/components/SW360Navbar/SW360Navbar.tsx
src/components/header/PageHeader.tsx

@hoangnt2 Please keep the proper componentns nomenclature as <component>/<component>.tsx
So in this specific PR, is SW360Navbar/SW360Navbar.txt, folder is the same name as component.

Restore navbar behavior and apply proper naming

---

src/app/[locale]/projects/add/page.tsx
src/assets/icons/trash.svg
src/components/AddAdditionalRoles.tsx
src/css/AddKeyValue.module.css
src/css/AddProjects.module.css

UI fixes in add project summary page

fix(add-project-summary): Ui fixes in add project summary page

---

src/styles/globals.css

- Changed the navbar underline hover color

fix(navbar): Fixed underline color and highlight in navbar

---

messages/en.json
messages/ja.json
messages/vi.json
messages/zh.json
src/components/sw360/FossologyClearing/FossologyClearing.tsx

This function will work when https://github.com/eclipse-sw360/sw360/pull/2047 was merged

feat(fossology): Handle fossology reload report

---

src/app/[locale]/components/components/ComponentIndex.tsx
src/app/[locale]/components/detail/[id]/components/ReleaseAggregate.tsx
src/app/[locale]/components/detail/[id]/components/SummaryRole.tsx
src/app/[locale]/components/detail/[id]/detail.module.css

**Changes:**
- Component Home page:
+ Export spreadsheet component with releases and without releases
- Component details page:
+ Fix styles
+ Fix moderators and vendors data

Handle export spreadsheet component, fix styles and data in component details page

---

src/app/[locale]/projects/add/page.tsx
src/components/ProjectAddSummary/Summary.tsx
src/components/ProjectAddSummary/component/Summary/GeneralInformation.tsx
src/components/sw360/SearchVendorsModal/VendorDialog.tsx
src/object-types/CreateProjectPayload.ts

Feature : Added onclick pop-up in vendor selection field while creating a project

feat(project): Added popup in vendor field on project creation page

---

src/app/[locale]/projects/add/page.tsx
src/components/ProjectAddSummary/Summary.tsx
src/components/ProjectAddSummary/component/AddKeyValue.tsx
src/object-types/CreateProjectPayload.ts

Feature :  Added the integration of external urls while creating a project

feat(project): Added external urls integration while creating project

---

src/app/[locale]/projects/add/page.tsx
src/components/ProjectAddSummary/Summary.tsx
src/object-types/CreateProjectPayload.ts

Feature : Added the integration of external ids while creating a project

feat(project): Added external ids integration while creating project

---

src/app/[locale]/components/edit/[id]/release/add/releases/AddRelease.tsx
src/app/[locale]/components/edit/[id]/release/add/releases/ReleaseAddSummary.tsx
src/object-types/Licenses.ts
src/object-types/ReleasePayload.ts
src/object-types/Repository.ts

feat(release): Add Release - Define Object Release

---

src/app/[locale]/components/edit/[id]/release/add/releases/ReleaseAddSummary.tsx
src/components/ReleaseSummary/ReleaseSummary.tsx
src/components/sw360/SearchContributors/ContributorsDiaglog.tsx
src/components/sw360/SearchContributors/ContributorsTable.tsx
src/components/sw360/SearchContributors/SelectTableContributors.tsx
src/components/sw360/SearchVendorsModal/SelectTableVendor.tsx
src/components/sw360/SearchVendorsModal/VendorDialog.tsx

Create Release
- Add search Vendor dialog
- Add search Contributor dialog

feat(release): Add search vendor, contributor diaglog

---

src/app/[locale]/components/edit/[id]/release/add/releases/AddRelease.tsx
src/app/[locale]/components/edit/[id]/release/add/releases/ReleaseAddSummary.tsx
src/components/LinkedReleases/LinkedRelesaes.tsx
src/components/ReleaseRepository/ReleaseRepository.tsx
src/components/ReleaseSummary/ReleaseSummary.tsx
src/components/sw360/SearchMainLicenses/MainLicensesDialog.tsx
src/components/sw360/SearchOtherLicenses/OtherLicensesDialog.tsx
src/components/sw360/SearchOtherLicenses/OtherLicensesTable.tsx
src/components/sw360/SearchOtherLicenses/SelectTableOtherLicenses.tsx

Create Release
- Get Data of Other License
- Get Data Linked Releases

feat(Release): Get Data Other License, Linked Releases

---

messages/en.json
src/app/[locale]/components/edit/[id]/release/add/releases/AddRelease.tsx
src/components/CommercialDetails/AddCommercialDetails.tsx
src/components/CommercialDetails/COTSOSSInformation.tsx
src/components/CommercialDetails/CommercialDetailsAdministration.tsx
src/object-types/COTSDetails.ts
src/object-types/ReleasePayload.ts

Create Release
- Get Data from tab Commercial Details

feat(release): Add Release - Get Data from tab Commercial Details

---

messages/en.json
messages/ja.json
messages/vi.json
messages/zh.json
src/app/[locale]/components/detail/[id]/components/ReleaseOverview.tsx
src/app/[locale]/components/editRelease/[id]/page.tsx
src/app/[locale]/components/editRelease/[id]/releases/EditRelease.tsx
src/app/[locale]/components/editRelease/[id]/releases/ReleaseEditSummary.tsx
src/app/[locale]/components/editRelease/[id]/releases/ReleaseEditTabs.ts
src/app/[locale]/components/releases/detail/[id]/components/DetailOverview.tsx
src/components/ReleaseSummary/ReleaseSummary.tsx
src/object-types/ReleasePayload.ts

Edit Release
- Create structure folder Edit Release
- Define state and props 
- Add UI release summary

feat(release): Create structure folder Edit Release

---

src/app/[locale]/components/edit/[id]/release/add/releases/AddRelease.tsx
src/app/[locale]/components/editRelease/[id]/releases/EditRelease.tsx
src/app/[locale]/components/editRelease/[id]/releases/ReleaseEditSummary.tsx
src/components/ReleaseSummary/ReleaseSummary.tsx
src/components/sw360/SearchLinkedReleases/SelectTableLinkedReleases.tsx
src/components/sw360/SearchMainLicenses/SelectTableMainLicenses.tsx
src/components/sw360/SearchOtherLicenses/SelectTableOtherLicenses.tsx
src/components/sw360/SearchVendorsModal/SelectTableVendor.tsx
src/utils/common.utils.ts

Edit Release
- Add UI additional Roles, External Ids, ....
- Set value for Release summary

feat(release): Edit Release - Set value for Release summary

---

src/app/[locale]/components/editRelease/[id]/releases/EditRelease.tsx
src/components/Attachments/EditAttachments.tsx
src/components/Attachments/SelectAttachment/SelectAttachment.tsx
src/components/Attachments/TableAttachment/TableAttachment.tsx
src/components/LinkedReleases/LinkedRelesaes.tsx
src/components/sw360/SearchLinkedReleases/LinkedReleasesDialog.tsx
src/object-types/ReleasePayload.ts

Edit Release 
- Set value for Linked Releases
- Set value for Attachments

feat(release): Edit Release - Set value for LinkedRelease, Attachments

---

src/components/LinkReleaseToProjectModal/LinkReleaseToProjectModal.tsx
src/components/sw360/AdvancedSearch/AdvancedSearch.tsx
src/styles/globals.css

1. Fix styling bug of inputs
2. Replace exact match tool tip by ShowInfoOnHover component
3. Add scroll bar to LinkReleaseToProjectModal when the content is too large

Fix styling

---

src/app/[locale]/components/editRelease/[id]/components/EditRelease.tsx
src/app/[locale]/components/editRelease/[id]/components/ReleaseEditSummary.tsx
src/object-types/ReleaseDetail.ts
src/utils/common.utils.ts

- Function common uitls
-  Get release for edit release

feat(eslint): Fix eslint errors for Edit Release page

---

src/app/[locale]/components/add/components/ComponentAddSummary.tsx
src/app/[locale]/components/edit/[id]/components/ComponentEditSummary.tsx
src/app/[locale]/components/edit/[id]/components/EditComponent.tsx
src/app/[locale]/components/edit/[id]/components/Releases.tsx
src/app/[locale]/components/edit/[id]/release/add/releases/AddRelease.tsx
src/app/[locale]/components/releases/detail/[id]/components/ClearingDetails.tsx
src/app/[locale]/components/releases/detail/[id]/components/DetailOverview.tsx
src/app/[locale]/components/releases/detail/[id]/components/ECCDetails.tsx
src/app/[locale]/components/releases/detail/[id]/components/ReleaseGeneral.tsx
src/app/[locale]/components/releases/detail/[id]/components/ReleaseVendor.tsx
src/app/[locale]/components/releases/detail/[id]/components/RequestInformation.tsx
src/app/[locale]/components/releases/detail/[id]/components/SupplementalInformation.tsx
src/object-types/Component.ts
src/object-types/EmbeddedAttachments.ts
src/object-types/EmbeddedLicense.ts
src/object-types/ReleaseDetail.ts
src/utils/common.utils.ts

-  Add/Edit Component
-  Release Detail

fix(release): fix eslint component/release

---

messages/en.json
messages/ja.json
messages/pt-BR.json
messages/vi.json
messages/zh.json
src/app/[locale]/projects/add/page.tsx
src/components/ProjectAddSummary/component/LinkedReleasesAndProjects/LinkedProjects.tsx
src/components/sw360/LinkedProjectsModal/LinkProjectsModal.tsx

Added dropdown for project relationship in link project, while creating a project

Added dropdown for project relationship in link project

---

src/components/sw360/Navbar/Navbar.tsx

- Modify navlist data to have id, visibility and child possibility
- Handle dropdown based entries dinamically like the rest of the navbar

refactor(navbar): Move hardcoded entries to more generic approach

---

src/app/[locale]/admin/vendors/components/AddVendor.tsx
src/app/[locale]/admin/vendors/components/VendorsList.tsx
src/app/[locale]/components/add/components/AddComponent.tsx
src/app/[locale]/components/components/ComponentIndex.tsx
src/app/[locale]/components/detail/[id]/components/DetailOverview.tsx
src/app/[locale]/components/edit/[id]/components/EditComponent.tsx
src/app/[locale]/components/editRelease/[id]/components/EditRelease.tsx
src/app/[locale]/components/releases/detail/[id]/components/DetailOverview.tsx
src/app/[locale]/licenses/LicensePage.tsx
src/app/[locale]/projects/add/page.tsx
src/app/[locale]/projects/components/Projects.tsx
src/app/[locale]/search/components/SearchPage.tsx
src/app/[locale]/vulnerabilities/add/components/AddVulnerability.tsx
src/app/[locale]/vulnerabilities/components/Vulnerabilities.tsx
src/components/sw360/AddAdditionalRoles/AddAdditionalRoles.tsx
src/middleware.tsx
src/styles/globals.css

This PR does several things:
- Fix some global css not working.
- Align page content
- Hide locales prefix (en, ja, ...) from URL
- Fix bug prop's value is undefined for AddAdditionalRoles

Fix page styling and component error, hide locale prefix from URL

---

src/app/[locale]/projects/detail/[id]/components/Administration.tsx
src/app/[locale]/projects/detail/[id]/components/ProjectDetailTab.tsx
src/app/[locale]/projects/detail/[id]/components/Summary.tsx
src/app/[locale]/projects/detail/[id]/page.tsx
src/object-types/AdministrationDataType.ts
src/object-types/SummaryDataType.ts

Accomodates changes made in eclipse-sw360/sw360#2145. The API changes were requested to improve UI performance and simplify code. We do not have to make a seperate fetch request for email and name of persons now.

fix(project_summary_administration): Change UI to accomodate API changes

---

src/components/sw360/AddAdditionalRoles/AddAdditionalRoles.tsx

Issue addressed : Adding an external role while creating  a project, it was breaking

fix(add_project): Fixed issus in add additional roles in add project summary page

---

src/app/[locale]/vulnerabilities/components/Vulnerabilities.tsx
src/object-types/Vulnerability.ts

Accomodates changes made in https://github.com/eclipse-sw360/sw360/pull/2166.

UI changes to accomodate pagination of vulnerabilities api

---

src/app/[locale]/preferences/components/TokensTable.tsx

Shows the generated token and expiration time according to the client's time zone

fix(Time): Shows the generated token and expiration time according to the client's time zone

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/preferences/components/NotificationSettingForm.tsx
src/app/[locale]/preferences/components/NotificationSettings.tsx
src/app/[locale]/preferences/components/TokensTable.tsx
src/app/[locale]/preferences/components/UserAccessToken.tsx
src/components/sw360/PageButtonHeader/PageButtonHeader.tsx

fix(Preferences): Add page button header, fix cannot update preferences

---

src/app/[locale]/projects/components/Projects.tsx
src/app/[locale]/projects/duplicate/[id]/components/DuplicateProject.tsx
src/app/[locale]/projects/duplicate/[id]/page.tsx

Added summary and admin page of duplicate project page

feat(duplicate_project): Added duplicate project page

---

src/components/sw360/Navbar/Navbar.tsx
src/styles/globals.css

- Fix bug nav bar links not working in production mode (cannot be clicked)
- Adjust nav bar styling

fix(Navbar): Fix bug cannot click navbar items in production mode

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/home/components/RecentComponentsWidget.tsx

Fixed recent components on home page

fix(home_page): Fixed recent components on home page

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/home/components/MyTaskAssignmentsWidget.tsx
src/object-types/ModerationRequest.ts
src/object-types/index.ts

Added my task assignments at home page

feat(home_page): Added my task assignments at home page

---

src/app/[locale]/home/components/MyTaskSubmissionsWidget.tsx

Note :  Yet to integrate the delete moderation request api.

feat(home_page): Added my task submissions at home page

---

src/app/[locale]/home/components/MySubscriptionsWidget.tsx
src/app/[locale]/home/components/RecentReleasesWidget.tsx
src/app/[locale]/search/components/SearchPage.tsx

Fixed redirection on clicking a release at home page and search page

fix(home_page): Fixed redirection on clicking a release at home page

---

src/app/[locale]/components/components/ComponentsTable.tsx
src/app/[locale]/projects/components/Projects.tsx
src/app/[locale]/vulnerabilities/components/Vulnerabilities.tsx
src/components/sw360/Table/Table.tsx

- Fixed bug incorrect table props are updated when the table is re-rendered
- Fixed an issue where tables using server paging were re-rendered multiple times (Project, Component, Vulnerability pages)

Fix table bugs

---

src/app/[locale]/projects/detail/[id]/components/ListView.tsx
src/app/[locale]/projects/detail/[id]/components/TreeView.tsx

Fixes:
1. Undefined/null reference errors.
2. Multiple rows for same project error.
3. Forever loading when an error occurs.

fix(licenseClearing): Fix bugs in project details license clearing table

---

src/app/[locale]/requests/moderationRequest/[id]/components/ModerationRequestDetail.tsx

Fixed http status condition for last moderator in unassign moderator at moderation request page

fix(moderation_request): Fixed http status condition for last moderator

---

src/app/[locale]/components/detail/[id]/components/ReleaseOverview.tsx
src/app/[locale]/components/releases/detail/[id]/components/ReleaseDetailTabs.ts
src/app/[locale]/requests/components/ClosedClearingRequest.tsx
src/app/[locale]/requests/components/ClosedModerationRequest.tsx
src/app/[locale]/requests/components/ExpandingModeratorCell.tsx
src/app/[locale]/requests/components/OpenClearingRequest.tsx
src/app/[locale]/requests/components/OpenModerationRequest.tsx
src/app/[locale]/requests/components/Requests.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/ModerationDecision.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/ModerationRequestDetail.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/ModerationRequestInfo.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/ProposedChanges.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/TableHeader.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/currentComponent/CurrentComponentDetail.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/currentRelease/CurrentReleaseDetail.tsx
src/app/[locale]/requests/moderationRequest/[id]/moderationRequestDetail.module.css
src/app/[locale]/requests/moderationRequest/[id]/page.tsx
src/app/[locale]/requests/page.tsx

Added component & release info under current component & release for moderation request

feat(moderation_requst): Added component & release info for Moderation Request

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/requests/moderationRequest/[id]/components/ModerationRequestDetail.tsx

Fixed toast message at open moderation request detail page

fix(moderation_request): Fixed toast message at open moderation request detail page

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/requests/components/Requests.tsx

Fixed moderation request count in button header title in the format below :
`MODERATIONS (Open moderation request count / Closed moderation request count)`

fix(moderation_request): Fixed moderation request count in button header title

---

src/app/[locale]/requests/components/OpenModerationRequest.tsx

Fixed error handling in date time conversion at open moderation request page

fix(MR): Fixed error handling in date time conversion in open moderation request

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/requests/components/Requests.tsx

Added separate button header titles for MR and CR at requests page

fix(CR): Fixed separate button header for MR and CR at requests page

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/components/releases/detail/[id]/components/DetailOverview.tsx
src/app/[locale]/components/releases/detail/[id]/components/ReleaseDetailTabs.ts
src/app/[locale]/components/releases/detail/[id]/components/spdx/AnnotationInformation.tsx
src/app/[locale]/components/releases/detail/[id]/components/spdx/CssButton.module.css
src/app/[locale]/components/releases/detail/[id]/components/spdx/DocumentCreationInformation.tsx
src/app/[locale]/components/releases/detail/[id]/components/spdx/OtherLicensingInformationDetectedDetail.tsx
src/app/[locale]/components/releases/detail/[id]/components/spdx/PackageInformationDetail.tsx
src/app/[locale]/components/releases/detail/[id]/components/spdx/RelationshipbetweenSPDXElementsInformation.tsx
src/app/[locale]/components/releases/detail/[id]/components/spdx/SPDXDocumentTab.tsx
src/app/[locale]/components/releases/detail/[id]/components/spdx/SnippetInformation.tsx

This is next PR of https://github.com/eclipse-sw360/sw360-frontend/pull/264
This PR implement the view of SPDX Document

Implement SPDX Document view in release detail page

---

src/app/[locale]/requests/moderationRequest/[id]/components/ProposedChanges.tsx

Fixed error handling in current and suggested value under proposed changes

fix(MR): Fixed error handling in current and suggested value under proposed changes

---

src/app/[locale]/requests/moderationRequest/[id]/components/ProposedChanges.tsx

Feature and Fixings :
-  Green color to identify newly coming data under proposed changes in a MR
-  Red color to identify deleting data under proposed changes in a MR

feat(MR): Added color coding for data additions and deletions

---

src/app/[locale]/requests/clearingRequest/[id]/components/ClearingDecision.tsx
src/app/[locale]/requests/clearingRequest/[id]/components/ClearingRequestDetail.tsx
src/app/[locale]/requests/clearingRequest/[id]/components/ClearingRequestInfo.tsx
src/app/[locale]/requests/components/OpenClearingRequest.tsx
src/object-types/ClearingRequestDetails.ts

Code refactoring for open CR table and open CR detail page

fix(CR): Code refactoring for open CR table and open CR detail page

---

src/app/[locale]/requests/components/ClosedClearingRequest.tsx
src/object-types/ClearingRequest.ts

Added closed CR table and populated with api response data

feat(CR): Added closed CR table

---

src/app/[locale]/projects/detail/[id]/components/CreateClearingRequestModal.tsx

Added feature to change preferred clearing date based on CR priority
- By default the requested clearing date will be T+d days later.
- But if `Critical` flag is checked while creating CR, user can select requested clearing date from T day itself.
Issue : https://github.com/eclipse-sw360/sw360-frontend/issues/267

feat(Create_CR): Added feature to change preferred clearing date based on CR priority

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/projects/detail/[id]/components/LicenseClearing.tsx
src/app/[locale]/projects/detail/[id]/components/ProjectDetailTab.tsx
src/app/[locale]/projects/detail/[id]/components/ViewClearingRequestModal.tsx
src/app/[locale]/requests/requestDetail.module.css
src/object-types/SummaryDataType.ts
src/object-types/enums/ClearingRequestStates.ts
src/object-types/index.ts

View CR:
- If a CR is in `OPEN` state : It will show `View Clearing Request` button and on click to it, it will show the existing CR details in a popup
- If a CR is in `CLOSED` state : It will disable the `Create Clearing Request` button.
- If a CR is in `IN_PROGRESS` state : It will show `Create Clearing Request` button and on click to it, it will ask the details to create a CR in a popup.

feat(View_CR): Added view CR details at license clearing of project detail page

---

src/app/[locale]/requests/components/OpenClearingRequest.tsx
src/styles/globals.css

Added edit button in open CR table
- If the project is not deleted, the button will show up and take it to edit CR page
- If the project is deleted, the edit button will not be shown in open CR table

feat(Open_CR): Added edit button in open CR table

---

src/app/[locale]/requests/components/ClosedClearingRequest.tsx

Added tooltip in CR status and clearing type in closed CR table

feat(Closed_CR): Added tooltip for closed CR table

---

nextauth.d.ts
src/app/api/auth/[...nextauth]/authOptions.ts
src/components/sw360/AuthScreen/AuthScreen.tsx
src/utils/env.ts

* Added a new custom OIDC/Oauth2 provider for authorization/authentication with the backend 
Closes #313

fix(auth): Oidc based authentication with backend

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/requests/clearingRequest/detail/[id]/components/ClearingDecision.tsx
src/app/[locale]/requests/clearingRequest/detail/[id]/components/ClearingRequestDetail.tsx
src/object-types/ClearingRequestDetails.ts

Added request closed on field in closed CR detail page

fix(CR_Details): Added request closed on field in closed CR detail page

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/requests/moderationRequest/[id]/components/ModerationRequestDetail.tsx
src/object-types/ModerationRequestPayload.ts

Features : 
- Postpone MR
- Fixed checking for mandatory comments for Accept, Reject and Postpone Moderation Request

feat(MR): Added feature to postpone mr

---

src/app/[locale]/projects/detail/[id]/components/AttachmentUsages.tsx
src/app/provider.tsx
src/object-types/AttachmentUsages.ts
src/object-types/Project.ts
src/object-types/Release.ts
src/object-types/index.ts

Project Details Attachment Usages Page

Attachment Usages

---

src/app/[locale]/admin/users/components/UserAdministration.tsx
src/app/[locale]/admin/vendors/components/VendorsList.tsx
src/app/[locale]/components/components/ComponentsTable.tsx
src/app/[locale]/licenses/components/LicensePage.tsx
src/app/[locale]/packages/components/Packages.tsx
src/app/[locale]/projects/components/Projects.tsx
src/app/[locale]/search/components/SearchPage.tsx
src/app/[locale]/vulnerabilities/components/Vulnerabilities.tsx
src/styles/globals.css

Makes the styling of index pages consistent

fix(Style): Makes the styling of index pages consistent

---

src/app/[locale]/home/HomePage.tsx
src/app/[locale]/home/components/HomeTableHeader.tsx
src/app/[locale]/home/components/MyComponentsWidget.tsx
src/app/[locale]/home/components/MyProjectsWidget.tsx
src/app/[locale]/home/components/MySubscriptionsWidget.tsx
src/app/[locale]/home/components/MyTaskAssignmentsWidget.tsx
src/app/[locale]/home/components/MyTaskSubmissionsWidget.tsx
src/app/[locale]/home/components/RecentComponentsWidget.tsx
src/app/[locale]/home/components/RecentReleasesWidget.tsx
src/app/[locale]/home/page.tsx
src/app/[locale]/page.tsx
src/components/sw360/AuthScreen/AuthScreen.tsx

Fix linter error for Home and Auth page

fix(Code): Fix linter error for Home and Auth page

---

src/app/[locale]/ecc/components/ECC.tsx
src/app/[locale]/ecc/page.tsx

fix(Code): Fix linter error for ECC page

---

src/app/[locale]/search/components/KeywordSearch.tsx
src/app/[locale]/search/components/SearchPage.tsx
src/app/[locale]/search/page.tsx

fix(Code): Fix linter error search page

---

src/app/[locale]/components/components/DeleteComponentDialog.tsx
src/app/[locale]/components/detail/[id]/components/DeleteReleaseModal.tsx
src/app/[locale]/projects/components/DeleteProjectDialog.tsx
src/components/sw360/SearchLinkedReleases/LinkedReleasesDialog.tsx

- Fix bug fetch data return 404 error at Component, Project, Release pages
- Fix bug search release modal not working

fix(Fetch): Fix bug fetch data return 404 error

---

src/app/[locale]/projects/detail/[id]/components/ProjectDetailTab.tsx
src/app/[locale]/projects/edit/[id]/components/EditProject.tsx

Clicking on edit button on a certain tab will open the corresponding edit tab

refactor(tabs): Clicking on edit button on a certain tab will open the corresponding edit tab

---

src/app/[locale]/projects/components/DeleteProjectDialog.tsx
src/app/[locale]/projects/components/Obligations/CompareObligation.tsx
src/app/[locale]/projects/components/Obligations/Obligations.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/LicenseObligation.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/ObligationsView.tsx
src/app/[locale]/projects/components/Projects.tsx
src/app/[locale]/projects/detail/[id]/components/Administration.tsx
src/app/[locale]/projects/detail/[id]/components/AttachmentUsages.tsx
src/app/[locale]/projects/detail/[id]/components/Attachments.tsx
src/app/[locale]/projects/detail/[id]/components/ChangeVulnerabilityModal.tsx
src/app/[locale]/projects/detail/[id]/components/Changelog.tsx
src/app/[locale]/projects/detail/[id]/components/Ecc.tsx
src/app/[locale]/projects/detail/[id]/components/LicenseClearing.tsx
src/app/[locale]/projects/detail/[id]/components/Obligations/ObligationsView/LicenseObligation.tsx
src/app/[locale]/projects/detail/[id]/components/ProjectDetailTab.tsx
src/app/[locale]/projects/detail/[id]/components/ProjectVulnerabilities.tsx
src/app/[locale]/projects/detail/[id]/components/Summary.tsx
src/app/[locale]/projects/detail/[id]/components/TreeView.tsx
src/app/[locale]/projects/detail/[id]/components/ViewClearingRequestModal.tsx
src/app/[locale]/projects/detail/[id]/components/VulnerabilityTab.tsx
src/app/[locale]/projects/detail/[id]/components/VulnerabilityTrackingStatus.tsx
src/object-types/AdministrationDataType.ts
src/object-types/LicenseClearing.ts
src/object-types/Obligation.ts
src/object-types/Project.ts
src/object-types/ProjectVulnerabilityTypes.ts
src/object-types/Release.ts
src/object-types/SummaryDataType.ts
src/object-types/index.ts

Removes linting errors from some pages in projects details section.

refactor(project_details): Remove linting errors in projects details

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/components/editRelease/[id]/components/EditRelease.tsx
src/app/[locale]/components/editRelease/[id]/components/ReleaseEditSummary.tsx
src/app/[locale]/components/editRelease/[id]/components/spdx/EditPackageInformation.tsx
src/app/[locale]/components/releases/detail/[id]/components/spdx/PackageInformationDetail.tsx
src/components/ReleaseSummary/ReleaseSummary.tsx
src/object-types/Release.ts
src/object-types/spdx/PackageVerificationCode.ts

- Fix bug cannot show release detail page because of undefined PackageVerificationCode
- Fix bug cannot update release when **NEXT_PUBLIC_SPDX_ENABLE=false**
- Handle create moderation request for non ADMIN user

Fix bugs for detail/edit release page

---

src/app/[locale]/projects/components/Projects.tsx
src/app/[locale]/projects/detail/[id]/components/Summary.tsx
src/app/[locale]/projects/edit/[id]/components/EditProject.tsx

1. [Project list] Fixes the issue preventing project deletion.
2. [Project list] Fixes the issue preventing clearing request creation.
3. [Update Project] Fixes missing data in the "Project Owner" field.
4. [Update Project] Displays the message "Success: You are editing the original project." when clicking the edit icon in the Project list.
---
- The user is logged in and there is at least one project in the Project list.
---
**Procedure:**
- Option 1: On the Project list page, click the delete button in the Action column to delete a project.
- Option 2: On the Update Project page, click the "Delete Project" button.
**Expected:**
+ A "Delete Project" dialog appears with the message "Do you really want to delete the project?"
+ The delete button is enabled.
+ The project is successfully …

fix(Projects): fix bugs in Project list

---

src/app/[locale]/components/detail/[id]/components/SummaryRole.tsx

Fix bug component owner is not showing on component detail page

fix(Component): Fix bug component owner is not showing on component detail page

---

src/components/ProjectAddSummary/component/Administration/LicenseInfoHeader.tsx

Fixed the alignment of default license info header button

fix(Project): Fixed the alignment of default license info header button

---

src/app/[locale]/projects/detail/[id]/components/LicenseClearing.tsx

Fixed view and create CR details at project page

fix(Project): Fixed view and create CR at project page

---

src/components/sw360/LinkedPackagesModal/LinkPackagesModal.tsx

Fixed redirection of licenses at link packages modal

fix(Project): Fixed redirection of licenses at link packages modal

---

src/app/[locale]/projects/detail/[id]/components/LinkedPackagesTab.tsx
src/app/[locale]/projects/edit/[id]/components/EditProject.tsx
src/components/ProjectAddSummary/LinkedPackages.tsx
src/components/sw360/LinkedPackagesModal/LinkPackagesModal.tsx
src/object-types/LinkedPackage.ts

Added feature to edit linked packages at edit project page

feat(project) : Added feature to edit linked packages at edit project page

---

src/app/[locale]/projects/detail/[id]/components/LicenseClearing.tsx

Added feature to export spreadsheet at license clearing tab of project detail page

feat(Project): Export spreadsheet at license clearing tab of project detail

---

src/app/[locale]/projects/detail/[id]/components/Ecc.tsx
src/app/[locale]/projects/detail/[id]/components/ProjectDetailTab.tsx

Feature to export spreadsheet at ECC tab of project detail page

feat(Project): Feature to export ecc spreadsheet at project detail page

---

src/app/[locale]/projects/components/Projects.tsx
src/components/sw360/AdvancedSearch/AdvancedSearch.tsx

Added advance search at project page

feat(Project): Added advance search

---

package.json
pnpm-lock.yaml

fix(NextJS): Upgrade NextJS to v15.2.2 to fix setting 'SHA224' error

---

src/app/[locale]/projects/components/ImportSBOMModal.tsx

Fixed an error in the fetching of error message for conflict status code and added additional check to confirm if a field exists in importSummary before calling length on it.

fix(ImportCDXStatus): conflict error message

---

package.json
pnpm-lock.yaml

Fixed this issue of `ERR_REQUIRE_ESM` while creating commits, by upgrading `commitlint` package version.

fix(config): Fixed ERR_REQUIRE_ESM error while creating commits

---

next.config.js
src/app/[locale]/projects/components/DeleteProjectDialog.tsx
src/app/[locale]/requests/moderationRequest/[id]/components/TableHeader.tsx
src/app/[locale]/vulnerabilities/components/AddValues.tsx
src/app/[locale]/vulnerabilities/components/DeleteVulnerabilityModal.tsx
src/components/LinkReleaseToProjectModal/LinkReleaseToProjectModal.tsx
src/components/LinkedObligations/TableLinkedObligations/DeleteObligationDialog.tsx
src/components/ReleaseSummary/ReleaseSummary.tsx
src/components/ResourcesUsing/ProjectsUsing.tsx
src/components/sw360/Navbar/Navbar.tsx

Fix build error and linter warning

Fix build error and linter warning

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/projects/components/Obligations/Obligations.tsx
src/app/[locale]/projects/detail/[id]/components/LicenseClearing.tsx
src/app/[locale]/projects/generateLicenseInfo/[id]/components/DownloadLicenseInfoModal.tsx
src/app/[locale]/projects/generateLicenseInfo/[id]/components/GenerateLicenseInfo.tsx

Feature to download project clearing report at `Obligations` tab

feat(project): Feature to download project clearing report at `Obligations` tab

---

src/app/[locale]/projects/components/Obligations/Obligations.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/ComponentObligation.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/ObligationsView.tsx
src/app/[locale]/projects/edit/[id]/components/EditProject.tsx
src/object-types/Obligation.ts
src/object-types/index.ts

Added component obligation at project details page
Note :
- Edit component obligation functionality yet to be implemented because it needs some API changes
closes issue : https://github.com/eclipse-sw360/sw360-frontend/issues/633

feat(Project): Added `Component obligation` at project detail

---

src/app/[locale]/home/components/MyProjectsWidget.tsx

feat(Home): Incorporate Approved Release column at My Projects table

---

src/components/sw360/Navbar/Navbar.tsx
src/object-types/NavItem.ts
src/object-types/NavList.ts

Added SW360_ADMIN role to access admin tab.
Closes issue : https://github.com/eclipse-sw360/sw360-frontend/issues/691

feat(Admin): Added SW360_ADMIN role to access admin tab

---

src/app/[locale]/components/components/ComponentsTable.tsx
src/app/[locale]/components/detail/[id]/components/ComponentTable.tsx
src/app/[locale]/components/detail/[id]/merge/components/GeneralSection.tsx
src/app/[locale]/components/detail/[id]/merge/components/MergeComponent.tsx
src/app/[locale]/components/detail/[id]/merge/components/RolesSection.tsx
src/app/[locale]/components/detail/[id]/split/components/ConfirmSplit.tsx
src/app/[locale]/components/detail/[id]/split/components/SplitData.tsx
src/app/[locale]/components/detail/[id]/split/components/SplitOverview.tsx
src/object-types/Component.ts
src/object-types/ListFieldProcessComponent.ts
src/object-types/index.ts

feat(split-components): Split components split and confirmation page

---

src/app/[locale]/admin/vendors/components/VendorsList.tsx

Added feature to export vendors at Admin page.
Closes issue : [eclipse-sw360/sw360-frontend/issues/545](https://github.com/eclipse-sw360/sw360-frontend/issues/545)

feat(Admin): Added feature to export vendors at admin page

---

src/app/[locale]/admin/vendors/merge/[id]/components/MergeData.tsx
src/app/[locale]/admin/vendors/merge/[id]/components/MergeOverview.tsx

feat(vendors): Merge vendors ui

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/projects/components/DeleteProjectDialog.tsx

Added feature to pass comment on popup to delete a project.
Closes issue : https://github.com/eclipse-sw360/sw360-frontend/issues/812

feat(Project): Added feature to pass comment on popup to delete a project

---

src/components/sw360/SearchUsersDialog/SelectUsersDialog.tsx

fix(search): Fix reset functionality

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json

Closes : https://github.com/eclipse-sw360/sw360-frontend/issues/844

fix(Licenses): Fixed translations at add license page

---

src/app/[locale]/admin/users/components/UserAdministration.tsx
src/app/[locale]/admin/users/page.tsx
src/components/sw360/AdvancedSearch/AdvancedSearch.tsx

- Fixed advanced search at users page
- Fixed enable/disable of `Exact Match` and `Orphan Package` filter at `Advanced Search`
Closes : [#837](https://github.com/eclipse-sw360/sw360-frontend/issues/837)  [#879 ](https://github.com/eclipse-sw360/sw360-frontend/issues/879)

fix(Users): Fixed advanced search at users page

---

src/app/[locale]/licenses/components/DeleteLicenseDialog.tsx

On delete license, the response will show proper messages.
- If the license in use, it will show on the popup : `Unable to delete license. License is in Use`
- Minor alignment and appearance updates
Closes : https://github.com/eclipse-sw360/sw360-frontend/issues/884

fix(Licenses): Fixed delete license with proper message

---

src/object-types/LicensePayload.ts

Fixed interface type mismatches

fix(Licenses): Fixed interface type mismatches

---

src/app/[locale]/components/components/ComponentsTable.tsx
src/components/sw360/Table/Components.tsx

refactor(components): Migrate table to tanstack table

---

messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ja.json
messages/ko.json
messages/pt-BR.json
messages/vi.json
messages/zh-CN.json
messages/zh-TW.json
src/app/[locale]/home/components/MyTaskAssignmentsWidget.tsx
src/app/[locale]/projects/detail/[id]/components/ChangeVulnerabilityModal.tsx
src/app/[locale]/projects/detail/[id]/components/ProjectVulnerabilities.tsx
src/app/[locale]/projects/detail/[id]/components/VulnerabilityTab.tsx
src/app/[locale]/vulnerabilities/components/Vulnerabilities.tsx
src/components/LicenseClearing.tsx
src/object-types/ProjectVulnerabilityTypes.ts

Migrate project vulnerability table

---

src/app/[locale]/components/components/ComponentsTable.tsx
src/app/[locale]/search/components/KeywordSearch.tsx
src/app/[locale]/search/components/SearchPage.tsx

refactor(search): Migrate search table to tanstack

---

src/app/[locale]/licenses/detail/components/LicenseDetailOverview.tsx

Fixed `Unexpected JSON input` error at `License` page
Closes : https://github.com/eclipse-sw360/sw360-frontend/issues/983

fix(Licenses): Fixed `Unexpected JSON input` error at license page

---

src/app/[locale]/projects/detail/[id]/components/VulnerabilityTrackingStatus.tsx
src/object-types/VulnerabilityTrackingStatus.tsx

refactor(project): Migrate vulnerability tracking status table to tanstack table

---

src/app/[locale]/projects/components/Obligations/ObligationsView/ComponentObligation.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/LicenseObligation.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/OrganizationObligation.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/ProjectObligation.tsx
src/app/[locale]/projects/components/Obligations/ObligationsView/UpdateCommentModal.tsx
src/app/[locale]/projects/edit/[id]/components/EditProject.tsx
src/object-types/Obligation.ts

Fixed obligation updates at edit project tab:
- `PATCH` api integration to update `Comment` and `Status` section of `License`, `Component`, `Project` and `Organization` obligations.
Closes : #1011

fix(Obligation): Fixed obligation updates at edit project comment

---

src/app/[locale]/projects/detail/[id]/components/ListView.tsx
src/app/[locale]/projects/detail/[id]/components/TreeView.tsx
src/components/sw360/Table/Components.tsx
src/components/sw360/index.ts

Migrate license clearing list view table to tanstack

---

src/app/[locale]/projects/detail/[id]/components/ViewClearingRequestModal.tsx
src/app/[locale]/requests/clearingRequest/detail/[id]/components/ClearingComments.tsx
src/app/[locale]/requests/clearingRequest/detail/[id]/components/ClearingDecision.tsx
src/app/[locale]/requests/clearingRequest/detail/[id]/components/ClearingRequestDetail.tsx
src/app/[locale]/requests/clearingRequest/detail/[id]/components/ClearingRequestInfo.tsx
src/app/[locale]/requests/clearingRequest/edit/[id]/components/EditClearingDecision.tsx
src/app/[locale]/requests/clearingRequest/edit/[id]/components/EditClearingRequest.tsx
src/app/[locale]/requests/clearingRequest/edit/[id]/components/EditClearingRequestInfo.tsx
src/app/[locale]/requests/components/OpenClearingRequest.tsx
src/object-types/ClearingRequest.ts
src/object-types/ClearingRequestDetails.ts
src/object-types/UpdateClearingRequestPayload.ts

Fixes are :
- Populated missing data in Open CR table
- Incorporated the missing fields at Edit CR page
Closes : https://github.com/eclipse-sw360/sw360-frontend/issues/1032

fix(CR): Fixed issues on `Clearing Request` page

---

src/app/[locale]/admin/vendors/components/VendorsList.tsx

refactor(vendors): Migrate vendors table to tanstack table

---

src/app/[locale]/admin/vendors/merge/[id]/components/MergeData.tsx
src/app/[locale]/admin/vendors/merge/[id]/components/MergeOverview.tsx
src/app/[locale]/admin/vendors/merge/[id]/components/VendorsTable.tsx

refactor(vendor): Migrate vendors merge table to tanstack table

---

src/app/[locale]/admin/databaseSanitation/components/DatabaseSanitation.tsx

Migrate database sanitation tables to tanstack table

---

src/app/[locale]/admin/departments/components/SecondaryDepartmentsTable.tsx

refactor(departments): Migrate secondary dept table to tanstack

---

src/app/[locale]/projects/components/Projects.tsx
src/styles/globals.css

Highlight projects with open CRs in the projects tab.

fix(CR): Highlight open CRs in projects tab

---

src/app/[locale]/admin/licenseTypes/components/LicenseTypesDetail.tsx

refactor(licensetypes): Migrate license types table to tanstack table

---

src/app/[locale]/components/edit/[id]/components/Releases.tsx

refactor(releases): Migrate add releases table to tanstack

---

src/app/[locale]/ecc/components/ECC.tsx

refactor(ecc): Migrate ecc table to tanstack

---

src/app/[locale]/components/releases/detail/[id]/components/LinkedPackagesTab.tsx

refactor(packages): Migrate release linked packages table to tanstack
